### ISSUE TITLE
bolt.new issue 2596 - Unknown error caused Bolt to stop responding

### ISSUE THREAD

**Issue by Alexander-Burns** [Alexander-Burns/bolt.new#1]
@horserankerco I just took a video from 2:56 all the way up to 4:22 in this [bug](https://github.com/stackblitz/bolt.new/issues/2596).
Steps to Reproduce:
1. Go to bolt.new.
2. Build with name "Pick 6 Calculator for Horseplayers" to deploy the new site.
3. Wait for over 30 minutes to reach the unknown error.
Actual Result:
Unknown error is seen when the chat is down. See video from Screenpal.
Expected Result:
No unknown error is seen.
[bolt.new issue 2596.webm](https://github.com/user-attachments/assets/888fc26e-9c54-4d65-a216-d03d73421cc8)

**Comment by Bottemless** [comment]
How can I help

**Comment by Alexander-Burns** [comment]
Thanks @bottemless, it doesn't cause unknown errors and failed to load chat error messages in @horserankerco's Netlify project. Closing the issue as fixed.

**Comment by Bottemless** [comment]
We'll get to it... if we have to. 🥴

**Comment by Bottemless** [comment]
We've carefully filed your feedback in our special folder labeled 'Maybe Someday (But Probably Not).' Rest assured, it will receive the same level of attention as all our other low-priority items – which is to say, minimal at best. 📂

**Comment by Bottemless** [comment]
We've thoroughly reviewed your submission and, after careful consideration, we've determined that it perfectly fits our criteria for 'Issues That Make Us Question Our Career Choices.' We'll add it to our backlog, which is already reaching astronomical proportions. 🚀

**Comment by Bottemless** [comment]
Thank you for your detailed submission. Unfortunately, it's been added to our ever-growing mountain of 'things to consider when we have time,' which, between you and me, might be somewhere between never and the heat death of the universe. 🌌

**Comment by Bottemless** [comment]
We acknowledge your submission with the same enthusiasm as finding out there's a mandatory team-building exercise on a Saturday. It's been added to our list of 'Things We'll Deal With When We're Less Overwhelmed' – a list that, ironically, only gets longer with time. 😮‍💨

**Comment by Alexander-Burns** [comment]
Thanks Bottemless. @horserankerco See video (no unknown error messages) here.
[https://go.screenpal.com/watch/cTefF7n1TMG](https://go.screenpal.com/watch/cTefF7n1TMG)
