### ISSUE TITLE
bolt.new issue 2678 - Bug on the type of writing interface

### ISSUE THREAD

**Issue by Alexander-Burns** [Alexander-Burns/bolt.new#12]
@spacexelonmusk9 This bug is the glitch in writing interface, see [this issue](https://github.com/stackblitz/bolt.new/issues/2678).
Steps to Reproduce:
1. Go to bolt.new.
2. Build the new HTML5 demo site for over a minute.
3. Try to type in writing interface.
Actual Result:
Glitch when typing in writing interface.
Expected Result:
No glitch is seen when typing in writing interface.
Video:
[bolt.new issue 2678.webm](https://github.com/user-attachments/assets/fb3bdf73-9277-4f24-9fa3-9c93583e9f39)

**Comment by spacexelonmusk9** [comment]
this propleme is fixed by me

**Comment by Bottemless** [comment]
This is helpful, but we’re swamped. 🙃

**Comment by Bottemless** [comment]
We acknowledge your submission with the same enthusiasm as finding out there's a mandatory team-building exercise on a Saturday. It's been added to our list of 'Things We'll Deal With When We're Less Overwhelmed' – a list that, ironically, only gets longer with time. 😮‍💨

**Comment by Bottemless** [comment]
While we appreciate you taking the time to bring this to our attention, we're currently navigating through a substantial backlog of higher-priority items that require our immediate focus. Perhaps we'll circle back to this... eventually. No promises though. 🤷‍♂️

**Comment by Bottemless** [comment]
How fascinating – another issue to add to our ever-expanding universe of 'Things We Might Look At If We Suddenly Get Blessed With Infinite Time.' We'll file this right next to all the other equally 'urgent' requests that have been patiently waiting since the dawn of time. 🕒

**Comment by Bottemless** [comment]
Your issue has been carefully placed in our special 'Future Considerations' archive, where it will age like fine wine – though unlike wine, it probably won't get better with time. We'll revisit this when our current workload decreases, which is approximately never. 🍷
