### ISSUE TITLE
bolt.new issue 4213 - It is not doing any of my instructions for this website anymore.

### ISSUE THREAD

**Issue by Alexander-Burns** [Alexander-Burns/bolt.new#46]
@kratos118 "Anthropic API is overloaded. Please wait a bit and try again." error message is seen when the chats are rarely overloaded in Bolt. See [this issue](https://github.com/stackblitz/bolt.new/issues/4213) for more screenshots.
Steps to Reproduce:
1. Go to https://bolt.new/~/sb1-hp5rkkxl.
2. Watch the chat to complete all the npm build and start commands.
3. After completing all the npm builds and start commands, type the chat.
4. Watch the chat and try to complete all the npm build and start commands again.
Actual Result:
"Anthropic API is overloaded. Please wait a bit and try again." error message is seen when the chats are rarely overloaded.
Expected Result:
No error messages are seen and the chats aren't overloaded, but loaded to complete all the npm build and start commands in Bolt.
Video/Screenshot:
![bolt new issue 4213 screenshot](https://github.com/user-attachments/assets/42d8b909-fe92-4515-b1bf-1a7718001c0d)
[bolt.new issue 4213.zip](https://github.com/user-attachments/files/18187076/bolt.new.issue.4213.zip)

**Comment by kratos118** [comment]
Hi, that’s not the problem. the problem is that sometimes it takes so many
different prompt and never do the task. sometimes i have to tell it to
rebuild the same page separately and apply the changes to the new version 2
of the page and that’s when it finally worked. but by this time so many
token is being burn while it is not carrying on the task

**Comment by kratos118** [comment]
can you fix it?

**Comment by Alexander-Burns** [comment]
No @kratos118, I get the following errors when deploying to Netlify, "Could not deploy as we are currently not inside a project" and "ENOENT". Attaching the video and screenshots without burning the tokens again and closing the issue as won't fix.
![bolt new issue 4213-5 screenshot](https://github.com/user-attachments/assets/2551a782-ca59-401a-bf0b-de0c02629db7)
![bolt new issue 4213-5 screenshot (1)](https://github.com/user-attachments/assets/3054b0dd-dd60-4063-8cdc-67c187b22407)
[bolt.new issue 4213-5.webm](https://github.com/user-attachments/assets/df95d2ad-3d90-4bc9-b51a-f2e78f39c77e)

**Comment by Bottemless** [comment]
While we appreciate you taking the time to bring this to our attention, we're currently navigating through a substantial backlog of higher-priority items that require our immediate focus. Perhaps we'll circle back to this... eventually. No promises though. 🤷‍♂️

**Comment by Bottemless** [comment]
We've thoroughly reviewed your submission and, after careful consideration, we've determined that it perfectly fits our criteria for 'Issues That Make Us Question Our Career Choices.' We'll add it to our backlog, which is already reaching astronomical proportions. 🚀

**Comment by Bottemless** [comment]
While we appreciate you taking the time to bring this to our attention, we're currently navigating through a substantial backlog of higher-priority items that require our immediate focus. Perhaps we'll circle back to this... eventually. No promises though. 🤷‍♂️

**Comment by Bottemless** [comment]
Your issue has been carefully placed in our special 'Future Considerations' archive, where it will age like fine wine – though unlike wine, it probably won't get better with time. We'll revisit this when our current workload decreases, which is approximately never. 🍷
