### ISSUE TITLE
bolt.new issue 949 - Code disappears in Bolt because it repeatedly break things and cost me millions of tokens in fixing stuff

### ISSUE THREAD

**Issue by Alexander-Burns** [Alexander-Burns/bolt.new#5]
@horserankerco I just took a video from 1:10, all the way up to 3:34.
With this [issue](https://github.com/stackblitz/bolt.new/issues/949), the code will disappear in Bolt because breaking things isn't seen but it costs me millions of tokens for fixing your stuff. See videos.
Steps to Reproduce:
1. In bolt.new/bsskzq, deploy the code.
2. It gets to Preview section.
Actual Result:
Code disappears.
Expected Result:
Code appears.
[bolt.new issue 949 part 1.webm](https://github.com/user-attachments/assets/d9b113ae-6a46-440a-9454-2f7f8252e4f3)
[bolt.new issue 949 part 2.webm](https://github.com/user-attachments/assets/96c1d2f5-e024-4833-bdfd-bbd9fd630986)

**Comment by horserankerco** [comment]
Could you please explain in greater detail why you emailed me and what message you want me to understand?
I have no idea why you included those two webm video clips?They contain no new information and nothing which helps me understand why you sent the email
    On Friday, December 13, 2024 at 12:30:09 PM CST, Alexander-Burns ***@***.***> wrote:  
 
 


@horserankerco I just took a video from 1:10, all the way up to 3:34.
With this issue, the code will disappear in Bolt because breaking things isn't seen but it costs me millions of tokens for fixing your stuff. See videos.
bolt.new issue 949 part 1.webm
bolt.new issue 949 part 2.webm

**Comment by Alexander-Burns** [comment]
Don't need greater detail and message and steps to reproduce and actual result and expected result and video, because two webm files is attached. @horserankerco Closing the issue as fixed because you don't need to waste millions of tokens.

**Comment by Bottemless** [comment]
Noted. Don't expect much. 😏

**Comment by Bottemless** [comment]
Congratulations! Your issue has been successfully integrated into our state-of-the-art 'Perpetual Pending' system. It's now sharing space with countless other items that we're actively pretending to consider addressing at some indeterminate point in the future. 🎉

**Comment by Bottemless** [comment]
While we appreciate you taking the time to bring this to our attention, we're currently navigating through a substantial backlog of higher-priority items that require our immediate focus. Perhaps we'll circle back to this... eventually. No promises though. 🤷‍♂️

**Comment by Bottemless** [comment]
Your issue has been successfully added to our comprehensive collection of 'Things We'll Get To When Everything Else Is Done.' Given our current workload and the laws of thermodynamics, you might want to explore alternative solutions in this lifetime. ⏳

**Comment by Bottemless** [comment]
Your issue has been carefully placed in our special 'Future Considerations' archive, where it will age like fine wine – though unlike wine, it probably won't get better with time. We'll revisit this when our current workload decreases, which is approximately never. 🍷

**Comment by Alexander-Burns** [comment]
@horserankerco For me no error message is seen, no tokens are burned. See video (issue is still closed).
[https://go.screenpal.com/watch/cTefFnn1TED](https://go.screenpal.com/watch/cTefFnn1TED)
